### ISSUE TITLE
cannot import name 'smiles2graph' from 'ogb.utils'

### ISSUE THREAD

**Issue by okpatil4u** [XiaoxinHe/Graph-ViT-MLPMixer#3]
Getting this error while running any of the modules. Should there be any requirements.txt for version controlled dependencies ?

**Comment by okpatil4u** [comment]
Changing the code in core/data_utils/peptides_functional.py line 8.

From 
`from ogb.utils import smiles2graph`

to
`from ogb.utils.mol import smiles2graph`

resolves this issue.

**Comment by XiaoxinHe** [comment]
Hi @okpatil4u ,
The "Python environment setup with Conda" in the README.md file has been updated and should have fixed the error.
