### ISSUE TITLE
ERROR: dependencies "ogb", "rdkit", "metis"

### ISSUE THREAD

**Issue by nurmuhimawann** [XiaoxinHe/Graph-ViT-MLPMixer#5]
Is there a special environment or library that you installed in this project? because I have problems running the run.sh script. can you include the requirements.txt files?

Previously, I had carried out the steps to set up the environment as you explained but still experienced an error when running your script.

**Comment by XiaoxinHe** [comment]
Could you please provide details about the issue you're facing? On my machines, those environments should be sufficient

**Comment by nurmuhimawann** [comment]
Solved, there are several libraries that are not compatible running on Windows. I have run on Linux, and it works.
