### ISSUE TITLE
About the configuration of metis

### ISSUE THREAD

**Issue by CurryTang** [XiaoxinHe/Graph-ViT-MLPMixer#6]
Thanks for your great project. I encountered some issues and would like to consult about the configuration of METIS. 

## Environments

> Same as the README.md

## Problem

 When I tried using MLP-Mixer on the Zinc dataset, I configured and compiled according to the METIS documentation, but a segmentation fault occurred when running MLPMixer on ZINC. 

```
os.environ['METIS_DLL'] = "xxx/metis/metis-5.1.0/build/Linux-x86_64/libmetis/libmetis.so"
```

```
CONFIG='train/configs/GraphMLPMixer/zinc.yaml'
python -m train.zinc --config $CONFIG device 1 model.gnn_type GINEConv    
```

I also tried replacing metis with the torch-sparse version and confirmed that the sizes of the metis subgraph and random subgraph are consistent (the random subgraph works perfectly). However, there were memory-related issues during the data loader process. I would like to ask for details regarding the configuration of METIS. Thanks!

```  python
new_edge_index, _ = dropout_edge(g.edge_index, drop_rate)
g.edge_index = new_edge_index
row, col = sort_edge_index(g.edge_index, num_nodes=num_nodes)
rowptr = index2ptr(row, size=num_nodes)
## conduct metis partition
cluster = pyg_lib.partition.metis(
        rowptr.cpu(),
        col.cpu(),
        n_patches,
        recursive=True,
    ).to(g.edge_index.device)
membership = cluster
```

with the following error 
```
malloc.c:4036: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
```

**Comment by XiaoxinHe** [comment]
Hi,

It appears that we might be using different METIS libraries. I am utilizing a third-party METIS library (see document [here](https://metis.readthedocs.io/en/latest/)), while you seem to be using the METIS supported by PyG.

Could you please confirm whether you have successfully installed METIS using the following commands:
```
# METIS
conda install -c conda-forge metis
pip install metis
``` 

Feel free to reach out if you have any further questions. Thanks!

**Comment by CurryTang** [comment]
Thanks for your response! I find that `conda install` will automatically compile the original METIS and now it works fine.
